spring:
  profiles: 
    active: dev
  concurrency:
    primes-in-range:
      num-threads: 3
    default:
      num-threads: 3
      max-thread-time-milliseconds: 2500
  rate-limit:
    anonymous:
      CAPACITY: 5
      REFILL_RATE: 1
    global:
      CAPACITY: 1000
      REFILL_RATE: 20
  logging:
    level:
      root: DEBUG
      org:
        hibernate: DEBUG
        springframework:
          orm:
            jpa: DEBUG
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  secret-key: 1bef3f99d2bf4abda0c27a68821a728f1bef3f99d2bf4abda0c27a68821a728f1bef3f99d2bf4abda0c27a68821a728f